=== czambel2/secret-avenger/data/superheroes.dtd
<?xml version="1.0" encoding="UTF-8"?>

		<!ELEMENT superheroes (superhero*)>
		<!ELEMENT superhero (nickname,firstName,lastName,universe,description,picture,superpowers,nemeses,lovers,sidekicks) >
		<!ATTLIST superhero id CDATA #REQUIRED>
		<!ATTLIST superhero wikipediaArticleName CDATA #IMPLIED>
		<!ATTLIST superhero slug CDATA #IMPLIED>

		<!ELEMENT nickname (#PCDATA)>
		<!ELEMENT firstName (#PCDATA)>
		<!ELEMENT lastName (#PCDATA)>
		<!ELEMENT universe (#PCDATA)>
		<!ATTLIST universe slug CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT picture (#PCDATA)>


		<!ELEMENT superpowers (superpower*)>
		<!ELEMENT superpower (#PCDATA)>


		<!ELEMENT lovers (lover*)>
		<!ELEMENT lover (#PCDATA)>
		<!ATTLIST lover firstName CDATA #IMPLIED>
		<!ATTLIST lover lastName CDATA #IMPLIED>


		<!ELEMENT nemeses (nemesis*)>
		<!ELEMENT nemesis (#PCDATA)>
		<!ATTLIST nemesis firstName CDATA #IMPLIED>
		<!ATTLIST nemesis lastName CDATA #IMPLIED>

		<!ELEMENT sidekicks (sidekick*)>
		<!ELEMENT sidekick (#PCDATA)>
		<!ATTLIST sidekick firstName CDATA #IMPLIED>
		<!ATTLIST sidekick lastName CDATA #IMPLIED>

=== czambel2/secret-avenger/data/superheroes.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE superheroes SYSTEM "superheroes.dtd">
<superheroes>
	<superhero id="1" wikipediaArticleName="Iron Man (comics)">
		<nickname>Iron Man</nickname>
		<firstName>Tony</firstName>
		<lastName>Stark</lastName>

		<universe>Marvel</universe>

		<description>
			<![CDATA[
				Iron Man (littéralement l'Homme de Fer) est un super-héros de comics créé en 1963 par Stan Lee pour
				Marvel Comics. Apparu pour la première fois dans Tales Of Suspense #39, la série était scénarisée par
				Larry Lieber et dessinée par Don Heck. À partir de 1968, le personnage a eu son propre comic qui a été
				publié par Marvel jusqu'en 1996 avec le no 332.
			]]>
		</description>

		<picture>iron-man.png</picture>

		<superpowers>
			<superpower>Armure en alliage</superpower>
			<superpower>Voler</superpower>
			<superpower>Lancer des lasers superpuissants</superpower>
		</superpowers>

		<nemeses/>

		<lovers>
			<lover firstName="Pepper" lastName="Potts"/>
		</lovers>

		<sidekicks>
			<sidekick firstName="" lastName="">Jarvis</sidekick>
		</sidekicks>
	</superhero>

	<superhero id="2" wikipediaArticleName="Veuve noire (comics)">
		<nickname>Black widow</nickname>
		<firstName>Natasha</firstName>
		<lastName>Romanova</lastName>

		<universe>Marvel</universe>

		<description>
			<![CDATA[
				La Veuve noire (Black Widow) est le nom de deux personnages d'espionne russe des comics Marvel. La
				première et la plus connue est Natalia Romanova ou Natasha Romanoff, d'abord apparue comme ennemie
				d'Iron Man dans Tales of Suspense #52 (1964), puis reconvertie en super-héroïne. Elle a été créée par
				Stan Lee, Don Rico et Don Heck.
			]]>
		</description>

		<picture>black-widow.png</picture>

		<superpowers/>

		<nemeses/>

		<lovers>
			<lover firstName="Connor" lastName="Hawke">Green Arrow</lover>
		</lovers>

		<sidekicks/>
	</superhero>

	<superhero id="3" wikipediaArticleName="Hulk">
		<nickname>Hulk</nickname>
		<firstName>Robert</firstName>
		<lastName>Banner</lastName>

		<universe>Marvel</universe>

		<description>
			<![CDATA[
				Hulk est un personnage de fiction appartenant à l'univers de Marvel Comics. Créé par Stan Lee et Jack
				Kirby, il est apparu pour la première fois dans le comic The Incredible Hulk #1 de mai 1962. Dans le
				classement du magazine Wizard, paru en juin 2008, Hulk a été classé dix-neuvième parmi les meilleurs
				personnages de comic books.
			]]>
		</description>

		<picture>hulk.png</picture>

		<superpowers>
			<superpower>Invincible</superpower>
			<superpower>Se transforme en géant vert</superpower>
		</superpowers>

		<nemeses/>

		<lovers/>

		<sidekicks/>
	</superhero>

	<superhero id="4" wikipediaArticleName="Thor (Marvel Comics)">
		<nickname>Thor</nickname>
		<firstName>Thor</firstName>
		<lastName>Odinson</lastName>

		<universe>Marvel</universe>

		<description>
			<![CDATA[
				Thor est un dieu et un super-héros appartenant à l'univers de Marvel Comics. Créé par l'éditeur Stan
				Lee, le scénariste Larry Lieber et le dessinateur Jack Kirby, ce personnage de fiction est apparu pour
				la première fois dans le comic book Journey into Mystery #83 (août 1962). C'est une divinité, un
				asgardien qui est basé sur son homologue dans la mythologie nordique.
			]]>
		</description>

		<picture>thor.png</picture>

		<superpowers>
			<superpower>Dieu</superpower>
			<superpower>Contrôle la foudre</superpower>
			<superpower>Peut manipuler Mjöllnir</superpower>
		</superpowers>

		<nemeses>
			<nemesis firstName="" lastName="">Géants de glace</nemesis>
		</nemeses>

		<lovers>
			<lover firstName="Jane" lastName="Foster"/>
		</lovers>

		<sidekicks/>
	</superhero>

	<superhero id="5" wikipediaArticleName="Batman">
		<nickname>Batman</nickname>
		<firstName>Bruce</firstName>
		<lastName>Wayne</lastName>

		<universe>DC</universe>

		<description>
			<![CDATA[
				Batman est un personnage de fiction créé par Bob Kane et Bill Finger dans Detective Comics #27 en mai
				1939. C'est un héros, à l'origine nommé "Bat-Man", qui a la particularité d’être sans pouvoirs. L'homme
				qui se cache sous ce costume est connu sous le nom de Bruce Wayne, bien que le costume et le nom aient
				été quelquefois utilisés par d'autres. Des surnoms lui sont parfois accolés : The caped crusader, The
				Dark Knight, The world greatest Detective.
			]]>
		</description>

		<picture>batman.png</picture>

		<superpowers>
			<superpower>Batmobile</superpower>
			<superpower>Ceinture de gadgets</superpower>
			<superpower>Costume de chauve-souris</superpower>
		</superpowers>

		<nemeses>
			<nemesis firstName="Joseph" lastName="Kerr">Le Joker</nemesis>
		</nemeses>

		<lovers>
			<lover firstName="Harleen" lastName="Quinzel">Harley Quinn</lover>
		</lovers>

		<sidekicks>
			<sidekick firstName="Jason" lastName="Todd">Robin</sidekick>
			<sidekick firstName="Alfred" lastName="Pennyworth">Alfred</sidekick>
		</sidekicks>
	</superhero>
</superheroes>
